/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpiryRouteImport } from './routes/expiry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIdRouteImport } from './routes/inventory.$id'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryRoute = ExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expiry': typeof ExpiryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/inventory/$id': typeof InventoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expiry': typeof ExpiryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/inventory/$id': typeof InventoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expiry': typeof ExpiryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/inventory/$id': typeof InventoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/expiry' | '/login' | '/pos' | '/reports' | '/inventory/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/expiry' | '/login' | '/pos' | '/reports' | '/inventory/$id'
  id:
    | '__root__'
    | '/'
    | '/expiry'
    | '/login'
    | '/pos'
    | '/reports'
    | '/inventory/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpiryRoute: typeof ExpiryRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  ReportsRoute: typeof ReportsRoute
  InventoryIdRoute: typeof InventoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiry': {
      id: '/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof ExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id': {
      id: '/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpiryRoute: ExpiryRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  ReportsRoute: ReportsRoute,
  InventoryIdRoute: InventoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
